### ISSUE TITLE
2 questions about the paper

### ISSUE THREAD

**Issue by nxznm** [gnodisnait/mushroom#1]
Hello, I want to ask 2 questions.
1. What the function of the type chains is in Algorithm 1?
2. I want to know whether I can use this method in the paper that makes all entities in KG into n-balls vectors. In Algorithm 2, I find that it tests every triple (h,r,x), and call nballs(h, r, tails, tChains, EV) function to get n-balls embedding, it seems that this paper doesn't focus on getting all entities' embedding at the same time. Am I wrong?
I'm sorry to bother you. Look forward to your reply and hope you have a nice day.

**Comment by HimmelStein** [comment]
very sorry for the delay (2 years, I noticed this question right now). you are right. this algorithm will not turn all KG entities into n-balls. we only extract a small tree, and turn the tree structure into containment relations among n-balls. quite simple.

**Comment by nxznm** [comment]
I got it. Thanks for your patience!
